// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Barre latérale commune aux trois instances de documentation (notes de cours,
 * échéancier, évaluations). `dirName: '.'` désigne la racine du dossier de
 * l'instance qui charge ce fichier : chacune génère donc sa propre arborescence
 * à partir de ses propres fichiers, et un seul fichier suffit ici.
 *
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  sidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
